// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQFoSvXMNr48Skcqbk8gi-nyq8NTSxXig',
    appId: '1:923247013542:web:77fbc945c3cdff98da4e67',
    messagingSenderId: '923247013542',
    projectId: 'chat-app-cdfb8',
    authDomain: 'chat-app-cdfb8.firebaseapp.com',
    storageBucket: 'chat-app-cdfb8.firebasestorage.app',
    measurementId: 'G-QPG5DFJJRH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKb_NDdKU-s4x0PeNRVM3-EotpNMZzgiY',
    appId: '1:923247013542:android:24a0b21c474aebebda4e67',
    messagingSenderId: '923247013542',
    projectId: 'chat-app-cdfb8',
    storageBucket: 'chat-app-cdfb8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQAXyyhhlWwO6uKmmAmPD3EbdxXN1Ferc',
    appId: '1:923247013542:ios:404ebfc93f5e42e3da4e67',
    messagingSenderId: '923247013542',
    projectId: 'chat-app-cdfb8',
    storageBucket: 'chat-app-cdfb8.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQAXyyhhlWwO6uKmmAmPD3EbdxXN1Ferc',
    appId: '1:923247013542:ios:404ebfc93f5e42e3da4e67',
    messagingSenderId: '923247013542',
    projectId: 'chat-app-cdfb8',
    storageBucket: 'chat-app-cdfb8.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );
}
